--------------------------------------------------------------------------------
Makelog started: 2022-07-28 11:36:24
Working directory: /oak/stanford/groups/gentzkow/jccp/sherlock_test/data
--------------------------------------------------------------------------------
Input links successfully created!
External links successfully created!
Source logs successfully written!
Executing command: `python  "/oak/stanford/groups/gentzkow/jccp/sherlock_test/data/code/merge_data.py" `
Traceback (most recent call last):
  File "/oak/stanford/groups/gentzkow/jccp/sherlock_test/data/code/merge_data.py", line 16, in <module>
    main()
  File "/oak/stanford/groups/gentzkow/jccp/sherlock_test/data/code/merge_data.py", line 8, in main
    df = merge_data(tv, chips)
  File "/oak/stanford/groups/gentzkow/jccp/sherlock_test/data/code/merge_data.py", line 12, in merge_data
    df = chips.merge(tv, on = 'county_id')
  File "/home/users/jccp/miniconda3/envs/template/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/users/jccp/miniconda3/envs/template/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/users/jccp/miniconda3/envs/template/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
    ) = self._get_merge_keys()
  File "/home/users/jccp/miniconda3/envs/template/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1096, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/users/jccp/miniconda3/envs/template/lib/python3.7/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'county_id'

